# Innledning {#intro}

Dette er ment å bli et verktøy for norske kommuner som ønsker å gjennomføre borgerpaneler.
I skrivende stund er den et levende arbeidsdokument til bruk i DEMOVATE-prosjektet.

## Hva er et borgerpanel?

Et borgerpanel er en samling av innbyggere i en kommune som kommer sammen og diskuterer en eller flere politiske saker.
Som vi skal komme inn på seinere er det en rekke måter man kan organisere et borgerpanel.
Vi fokuserer på det kommunale nivået, og situasjoner hvor politikerne i kommunen ønsker å ta initiativ til borgerpanel som et redskap for å lytte til innbyggerne.

En variant av borgerpaneler er Deliberativ meningsmåling, som blir grundig dekket i denne håndboken.
Vi gjennomfører våren 2021 en deliberativ meningsmåling i samarbeid med grunnleggeren av prosedyren, Professor James F. Fishkin ved Stanford University.
På grunn av situasjonen med koronapandemien blir denne gjennomført online.

I tillegg gjennomfører vi to andre borgerpaneler som ikke er deliberative meningsmålinger høsten 2021.
Disse tar vi sikte på kan bli arrangert hvor deltakerne er fysisk tilstedeværende.

## Organisering av håndboken
<!-- Etter introduksjonen følger et kapittel som diskuterer motivasjonen for å gjennomføre et borgerpanel. -->
<!-- Vi kommer inn på både dets styrker og svakheter, og borgerpanelets rolle i det demokratiske systemet. -->
<!-- Kapittel fire beskriver gjennomføringen av en online deliberativ meningsmåling i Bergen kommune, våren 2021. -->
<!-- Kapittel fem beskriver gjennomføringen av to fysiske borgerpaneler høsten 2021. -->

Mer kommer.
