# Saker

Hvilke(n) saker som skal diskuteres i en deliberativ meningsmåling
## Tre kriterier
For å få til et vellykket arrangement bør sakene som velges tilfredsstille følgende kriterier.
De bør være

1. Nyttige for kommunen

2. Velegnet for metoden

3. Interessante for deltakerne

Sakene bør være nyttige for kommunen slik at svarene deres faktisk blir brukt inn i den politiske prosessen.
At sakene er velegnet for metoden betyr at man kan anta at man får bedre svar om man snakker sammen først enn om man bare spør på direkten. 
Folks holdninger i enkelte saker er sterkt innarbeidet og vanskelig å rikke på, mens i andre saker kan folk være mer mottakelig for innspill og diskusjon.
Til sist bør sakene også være interessante nok for deltakerne til at de tar seg bryet med å delta.
Om sakene blir for snevre eller lite engasjerende, risikerer man at de som deltar er mindre representative for populasjonen.

Om deltakerne skal diskutere flere saker kan disse utfylle hverandre, slik at de samlet sett oppfyller disse tre kriteriene.

## Saker som har vært diskutert i prosjektet

Siden oppstarten av prosjektet har vi vært innom en rekke saker som kan være aktuelle.
Vi nevner under de sakene som har vært mest seriøst diskutert

### Turistskatt
Det har vært oppe til diskusjon om man skal innføre skatt på cruiseturismen i Bergen. 
Skatten skal gå til vedlikehold av fasiliteter som turistene bruker. 
Hvor sterkt støtter eller motsetter du deg en slik turistskatt?

### Boligbygging på Store Lungegårdsvann
Det har i enkelte avisinnlegg blitt tatt til orde for å bygge boliger på deler av Store Lungegårdsvann. 
Hvor sterkt støtter eller motsetter du deg at dette gjøres?

### Terrorbekjempelse
Hvor enig er du i følgende påstand: 
Myndighetene bør innføre flere tiltak for å beskytte borgere mot potensielle terrortrusler, selv om dette kan gå på bekostning av personvernet.

### Redusere økonomiske forskjeller
Byrådet bør jobbe for å i større grad redusere økonomiske forskjeller i samfunnet.

### Tiggerforbud
Det bør innføres forbud mot tigging på gaten i Bergen.

### Arealstrategi for Dokken 

Dette delprosjektet skal utarbeide en arealstrategi som er i tråd med den overordnede strategien for Dokken.

-	Vise hoveddisponering av området og gi grunnlag for politisk prinsippvedtak om byplangrep i 2021.  
-	Være en konkretisering av de overordnede visjonene, i form av byutviklingskonsept.  
-	Legge grunnlag for byutviklingsgrep i kommende juridisk arealplan(er).  
-	Legge et grunnlag for trinnvis omsetning av eiendommer innenfor området, fortrinnsvis de kommunale.  
-	Muliggjøre trinnvis utvikling av området. 

### Bilfrie soner i bydelene

Dette prosjektet er nylig startet opp, skal bygge kunnskap i tiden fremover, og konkretiserer arbeidet først i 2022. 
Med forbehold om endringer i skissen, så skal det etter planen velges en pilot i en av de ytre bydelene innen februar 2021.
For å løse oppdraget om å realisere bilfrie soner i bydelene har det blitt definert behov for to hovedprosesser; kartlegging og utvikling. 
I tillegg vil det gjennom hele prosjektet ha fokus på kunnskapsbygging for å utvikle metoder og strategier for å velge ut områder og utvikle bilfrie soner. 
Med andre ord handler prosjektet både om prosess og innhold. 
