---
output:
  word_document: default
  html_document: default
---
**Hvorfor kontakter vi deg? **

Vi kontakter deg for å invitere deg til å delta i dette arrangementet. 
Du er trukket tilfeldig fra Folkeregisteret, basert på informasjon om din alder, kjønn og adresse.
Det er viktig for oss å beskytte personopplysningene dine. 
Denne informasjonen skisserer hva vi gjør med dataene som vi samler inn og lagrer. 

**Din deltakelse i arrangementet**

I løpet av arrangementet vil du delta i nettbaserte gruppediskusjoner om lokale samfunnsspørsmål.
Det vil også være eksperter som vil kunne svare på spørsmål fra gruppen.

Inviterte gjester kan se og lytte til diskusjonene underveis.
Det vil gjøres lydopptak av diskusjonene.
Opptakene knyttes ikke til annen informasjon som blir samlet inn, og blir midlertidig lagret på Stanford University i USA før de blir anonymisert. 

I de tilknyttede spørreundersøkelsene vil vi spørre om politikk, din bakgrunn, og om dine holdninger i utvalgte lokale samfunnsspørsmål. 

Det er frivillig å delta i undersøkelsen. 
Du bestemmer selv hvilke spørsmål du vil svare på, og du kan avslutte din deltakelse når som helst uten å oppgi noen forklaring.
Alle opplysninger om deg vil da bli anonymisert. 
Det vil ikke ha noen negative konsekvenser for deg hvis du ikke vil delta eller senere velger å trekke deg. 

**Hvis du bestemmer deg for å ikke delta**

Vi har behov for å kontrollere at personene som deltar i undersøkelsen er representative for den samlede befolkningen. 
Når vi trakk utvalget innhentet vi informasjon om hvilken ditt navn, adresse, telefonnummer, kjønn, alder og utdanning.
Dine kontaktopplysninger er hentet fra Folkeregisteret med tillatelse fra Skatteetaten.
Du har rett til innsyn i disse opplysningene, samt be om at opplysningene korrigeres eller slettes.
Hvis du bestemmer deg for å ikke delta i arrangementet, vil vi bruke disse dataene i anonymisert form til å gjøre en frafallsanalyse.
Du kan reservere deg mot å være del av frafallsanalysen ved å kontakte Pål Bjørseth i Bergen kommune (se kontaktinfo lenger oppe i invitasjonsbrevet).
Nedenfor finner du informasjon om personvernet og rettighetene dine.

**Hva skjer med informasjonen som samles inn?**

*	Vi vil behandle all informasjon om deg strengt konfidensielt og i samsvar med EUs personvernforordning (GDPR) og nasjonale personvernlover.
Prosjektet er meldt til  personvernombudet ved Norsk senter for forskningsdata (NSD).  
* Vi vil bare bruke opplysningene om deg til formålene vi har fortalt om i dette skrivet.  
*	Det er bare de involverte organisasjonene som samler inn dataene, som vil ha tilgang til kontaktopplysningene dine (f.eks. navn, adresse og telefonnummer).
Direkte og indirekte identifiserbare personopplysninger lagres på en sikker server ved UiB (SAFE – Sikker Adgang til Forskningsdata og E-infrastruktur) og i KS sitt PostUt verktøy (kommunens verktøy for å sende brev til DigiPost). 
Ettersom programvaren vi benytter er utviklet og drevet av Stanford University i USA, vil noen av dataene sendes midlertidig ut av EU.
De blir forsvarlig oppbevart etter Stanford Universitys sikkerhetsregler for lagring av data.  
Spørreskjemaopplysningene behandles av Qualtrics International Inc., USA. 
Vi benytter Qualtrics sin anonyme løsning hvor det ikke lagres kobling mellom IP-/e-postadresse og besvarelse. 
Følgende personer ved behandlingsansvarlige institusjoner vil ha tilgang til dine opplysninger: Sveinung Arnesen (NORCE),  Anne Lise Fimreite (UiB), Jacob Aars (UiB), Jon Kåre Skiple (NORCE), Henrik Litleré Bentsen (NORCE), Alice Siu (Stanford University), Lodewijk Gelauff (Stanford University).  	
*	Når arrangementet er ferdig, og senest 31.12.2021 vil alle personidentifiserbare opplysninger slettes permanent. 
Dataene, uten navnet eller kontaktopplysningene dine, sendes NSD – Norsk senter for forskningsdata i Bergen.   
*	De anonymiserte dataene lagres sikkert på ubestemt tid. 
De gjøres tilgjengelig for bruk i vitenskapelige studier av forskere, studenter og andre.  
<!-- *	Det er en mulighet for, selv om det er usannsynlig, at noe informasjon kan kombineres på en måte som kan identifisere deg.  -->
<!-- Dette gjelder kun data som ikke er publisert.  -->
<!-- Tilgang til disse dataene vil bare bli gitt til forskere etter at godkjente søknader og konfidensialitetsavtaler er på plass.   -->
*	Resultatene av undersøkelsen vil bli publisert på nettsiden til forskningsprosjektet innen januar 2022.     
*	Vi vil gjøre vårt ytterste for å sikre at ingen deltakere kan identifiseres i resultatene fra undersøkelsen, eller i noen publikasjoner som bygger på studien. 

**Dine rettigheter**

Så lenge du kan identifiseres i datamaterialet, har du rett til:  
-	innsyn i hvilke personopplysninger som er registrert om deg,  
-	å få rettet personopplysninger om deg,   
-	få slettet personopplysninger om deg,  
-	få utlevert en kopi av dine personopplysninger (dataportabilitet), og  
-	å sende klage til personvernombudet eller Datatilsynet om behandlingen av dine personopplysninger.  

**Hva gir oss rett til å behandle personopplysninger om deg?**  

Vi behandler registeropplysninger om deg med dispensasjon fra taushetsplikten fra Statistisk sentralbyrå, basert på allmenn interesse og offentlig myndighet (art. 6 nr. 1 bokstav e) og formål knyttet til vitenskapelig forskning (art. 9 nr. 2 bokstav j). Vi behandler opplysninger som innhentes i utførelsen av Byborgerpanelet med bakgrunn i samtykke.

På oppdrag fra Bergen kommune, UiB og NORCE har NSD vurdert at behandlingen av personopplysninger i dette prosjektet er i samsvar med personvernregelverket. 
Når detaljer som ditt navn, adresse og telefonnummer er fjernet, er det ikke lenger mulig å slette informasjonen du har oppgitt. 
Dette er fordi det ville kreve en betydelig innsats å identifisere deg gjennom de gjenværende opplysningene, etter at de nevnte opplysningene er fjernet.
Du har også rett til å sende en klage til Datatilsynet.

**Hvem er ansvarlig?**

Det er NORCE - Norwegian Research Centre, Bergen kommune, Universitetet i Bergen og Stanford University som gjennomfører undersøkelsen og er felles behandlingsansvarlig.
Prosjektet finansieres av Bergen kommune og Norges Forskningsråd (prosjektnummer: 295892). 

**Hvilke organisasjoner er involvert?**

Bergen kommune, NORCE - Norwegian Research Centre, Universitetet i Bergen og Stanford University er involvert i prosjektet som organiserer arrangementet.
Norges forskningsråd finansierer prosjektet. 

**Hvor kan jeg finne ut mer?**

Du kan finne ut mer om studien ved å gå inn på nettsiden www.xxxx.no.
Du kan også kontakte disse personene direkte, på epost eller telefon:

*Kontakter:*

Bergen kommune: Pål Bjørseth, e-post: pal.bjorseth@bergen.kommune.no, telefon xxxx.

Personvernombud, Bergen kommune: 

NORCE: Sveinung Arnesen, e-post: sveinung.arnesen@norceresearch.no, telefon +47 99 53 24 96.  

Personvernombud, NORCE (behandlingsansvarlig): Øyvind Straume, e-post: personvernombud@norceresearch.no


 

<script src="https://yihui.name/js/center-img.js"></script>
