##### R2DEMOVATE10  

> Merkelapp: Mulighet til å påvirke politikk

I hvilken grad vil du si at det politiske systemet i Bergen gir folk som deg innflytelse på det lokale myndigheter gjør? Vennligst velg blant alternativene under hvor 0 betyr «ikke i det hele tatt» og 10 betyr «fullt og helt».

0 Ikke i det hele tatt  
1  
2  
3  
4  
5   
6  
7  
8  
9  
10 Fullt og helt  

##### R2DEMOVATE11: 

> Merkelapp: Politikk er komplisert

Hvor godt passer følgende utsagn, slik du ser det: Lokalpolitikken er i blant så innviklet at folk som meg ikke forstår hva den dreier seg om. Vennligst velg blant alternativene under hvor 0 betyr «passer ikke i det hele tatt» og 10 betyr «fullt og helt».

0 Ikke i det hele tatt  
1  
2  
3  
4  
5   
6  
7  
8  
9  
10 Fullt og helt  

##### R2DEMOVATE12

> Merkelapp: Plassering på politisk skala>  

I politikken snakker man ofte om "venstresiden" og "høyresiden". Nedenfor er en skala der 0 representerer de som står helt til venstre politisk, og 10 representerer de som står helt til høyre politisk.  

Hvordan vil du plassere deg selv på en slik skala?  
  
0 Venstre  
1  
2  
3  
4  
5  
6  
7  
8  
9  
10 Høyre  

##### R2DEMOVATE20

> Info: Spørsmålsbatteri. 
Merkelapp: Hjertesak

Hvor viktig vil du si at følgende saker var for velgernes stemmegivning ved kommunevalget i din kommune?

Skole
Eldreomsorg
Kommunesammenslåinger
Eiendomsskatt
Kultur/idrett
Miljø/klima
Kollektivtilbud
Sammenslåing av fylkeskommuner
Innvandring 
Arealutnyttelse

0 Svært lite viktig
1
2
3
4
5
6
7
8
9
10 Svært viktig

#### Bakgrunnsspørsmål

##### R2DEMOVATE26

Merkelapp: Bydel

Hvor i Bergen bor du?
1.	Arna
2.	Åsane
3.	Ytrebygda
4.	Fana
5.	Laksevåg
6.	Fyllingsdalen
7.	Årstad
8.	Bergenhus

##### R2DEMOVATE18

> Merkelapp: Høyest fullførte utdanning>

Hva er din høyest fullførte utdanning?

- Ingen utdanning/grunnskole  
- Videregående skole  
- Høgskole/Universitet (minst 2 år)  


##### R2DEMOVATE19

> Merkelapp: Inntekt

Hva er inntekten din for tiden? Brutto årsinntekt i kroner er:

- Under 150 000  
- 150 001 - 300 000  
- 300 001 - 400 000  
- 400 001 - 500 000  
- 500 001 - 600 000  
- 600 001 - 700 000  
- 700 001 - 1 000 000   
- Over 1 000 000


##### R2DEMOVATEaldrkat

> Merkelapp: Alderskategori.

Hva er din alder?

1.	Under 30 år
2.	30-44 år
3.	45-59 år
4.	60 år eller eldre


##### R2DEMOVATE21

> Merkelapp: Kjønn. Randomisér svaralternativene.

Hva er ditt folkeregistrerte kjønn?

- Kvinne

- Mann

##### R2DEMOVATEaldrkat

> Merkelapp: Alder

Hva er din alder?

1.	Under 30 år
2.	30-44 år
3.	45-59 år
4.	60 år eller eldre

##### R2DEMOVATEStatsborgerskap

Statsborgerskap. Er du:  

1 Norsk statsborger  
2 Statsborger i annet land. Vennligst skriv hvilket  

##### R2DEMOVATEinnvandret

Har du eller dine foreldre (mor, far eller begge foreldre) innvandret til Norge?
 
Nei  
Jeg har selv innvandret til Norge  
Begge mine foreldre har innvandret til Norge, men jeg er født i Norge  
Mor har innvandret til Norge, men jeg og min far har ikke innvandret  
Far har innvandret til Norge, men jeg og min mor har ikke innvandret  

##### R2DEMOVATEstemmerett
 
Hadde du stemmerett ved Kommunestyrevalget i 2019?

Ja  
Nei  
Vet ikke

