#### Zoom

##### Personvern

Universitetet i Bergen har en samarbeidsavtale med Zoom, og bruken av Zoom kommer derfor ikke i konflikt med Schrems II-dommen om overføring av data ut av EU/EØS. (Anne Lise sjekker opp)


##### Bruk av Zoom på arrangementsdagen

-	Om lag 200 deltakere, pluss/minus 100
-	Dagen deles inn i to hovedsesjoner, hver med tre perioder.
Mellom hovedsesjonene er det en times lunsjpause

1. Bilfrie soner
  
  a) Gruppediskusjon. Varighet: 60 minutter
  
  b) Paneldiskusjon i samtale med eksperter. Varighet: 45 minutter
  
  c) Gruppediskusjon. Varighet: 30 minutter
  
2. Arealutvikling på Dokken

  a) Gruppediskusjon. Varighet: 60 minutter
  
  b) Paneldiskusjon i samtale med eksperter. Varighet: 45 minutter
  
  c) Gruppediskusjon. Varighet: 30 minutter
  
-	Gruppediskusjonene foregår med om lag ti deltakere pluss en gruppeleder.
Gruppene er bestemt på forhånd, og finnes på en deltakerliste. 
Vi må ha en løsning som raskt kan matche Zoom-brukerne med deltakerne på denne listen, slik at inndelingen i grupper skjer rimelig raskt.

-	I paneldiskusjonene kommer alle sammen i samme virtuelle rom.
2-4 eksperter svarer på spørsmål fra moderator og fra deltakerne.

- Gruppediskusjonene i punkt c) skal være de samme som i punkt a)

- Vi antar det vil være behov for en del teknisk støtte hos deltakerne.
Deltakerne representerer et tverrsnitt av innbyggerne i Bergen, og datakyndigheten likeså.

- Det vil være en fordel om deltakerne kan prøve ut utstyret sitt og lenken på forhånd. Gjerne de siste 48 timene før arrangementsdagen, for eksempel.



