---
title: "Deliberative Poll, Bergen"
subtitle: "Schedule for June 12, 2021"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup-dagsplan, include=FALSE}

if(!require(kableExtra)) {install.packages('kableExtra'); require(kableExtra)}
if(!require(knitr)) {install.packages('knitr'); require(knitr)}
if(!require(tidyverse)) {install.packages('tidyverse'); require(tidyverse)}

knitr::opts_chunk$set(echo = FALSE, knitr.kable.NA = " ", warning = FALSE, message = FALSE)
```

```{r dagsplan, include=FALSE}

dagsplan <- tibble(Start = c('10:00', '10:10', '11:00', '11:50', '12:30', '13:15', '14:10', '15:05', '15:50'),
                     Stop = c('10:10', '10:55', '11:45', '12:30', '13:15', '14:00', '14:55', '15:50', '16:00'),
                         Activity = c('Welcome', "Dokken: First Group Session", "Plenary Session", "Dokken: Second group Session", "Lunch", "Car Free Zones: First Group Session", "Plenary Session", "Car Free Zones: Second Group Session", 'Concluding Remarks'),
                   beskrivelse = c('',
                                   'Opptelling av deltakere, gjennomgang av agenda, forberede spørsmål til panel',
                                   'Moderator:  Anne Lise Fimreite. Paneldeltakere: Anders Nyland, Johanne Gillow, Gro Sandkjær Hanssen, Erling Dokk Holm',
                                   'Debrief og videre diskusjon i gruppen', ' ', 
                                   'Gjennomgang av agenda, forberede spørsmål til panel',
                                   'Moderator: Jacob Aars. Paneldeltakere: Oddrun Hagen, Håvard Haarstad, Rolf Knudsen',
                                   'Debrief og videre diskusjon i gruppen.', 'Avslutning')
                   )
```

```{r tabell-dagsplan}
dagsplan  %>%  select (-beskrivelse) %>% kable(linesep = "",
      booktabs = T, 
      escape = F) %>% 
  kable_styling() %>% 
  collapse_rows(3)  
  
```
