---
title: "Velkommen"
author: "Sveinung Arnesen"
date: "6/10/2021"
output: html_document
---

Hei alle, og velkommen til denne deliberative meningsmålingen.

Mitt navn er Sveinung Arnesen, og jeg er faglig leder for dette arrangementet.
Arrangementet er del av et demokratiprosjekt ledet av Bergen kommune og Norce, i samarbeid med Universitetet i Bergen og Stanford University.
Vi er glade for å se så mange engasjerte innbyggere i Bergen møtes for å diskutere byens framtid!
Og værgudene har vært med oss og gitt oss supert innevær.

Dere har fått utdelt dagsplanen som viser løpet for dagen.
For å holde skjemaet vil tidspunktene følges strengt.

Først skal vi diskutere Dokken, og deretter skal vi diskutere bilfrie områder.
Vi starter først med en gruppediskusjon, før paneldebatten om Dokken settes i gang av Anne Lise Fimreite.
Paneldeltakerne der er Gro Sandkjær Hanssen, Anders Nyland, Johanne Gillow, og Erling Dokk Holm.
Dere vil i gruppediskusjonene få anledning til å lage spørsmål til panelet, og noen av disse vil bli stilt til panelets deltakere.

Etter panelet fortsetter gruppediskusjonen om Dokken.
Så blir det lunsjpause.

Programmet etter pausen følger samme oppsett for bilfrie områder.
Moderator for paneldebatten er Jacob Aars, og han har med seg i panelet Håvard Haarstad, Oddrun Hagen, og Rolf Knudsen.

Dere vil straks bli delt inn i grupper, og sendt til mindre grupperom.
I grupperommet vil dere bli introdusert for de andre deltakerne. 
Vi har gruppeledere i hvert rom.
Gruppelederne vil hjelpe dere å komme i gang med diskusjonen, men det er dere som deltakere som skal diskutere med hverandre.
Gruppelederne er der bare for å legge til rette.
Det kan også hende det kommer innom noen observatører i løpet av gruppediskusjonen.
Dette er prosjektmedlemmer og andre interesserte som bare skal følge med på diskusjonen, og ikke selv delta i den.

Vi oppfordrer om at alle viser respekt for hverandre, selv om man kan ha ulike synspunkter på sakene som diskuteres.
Husk at dere ikke trenger å bli enige, det viktige her er at man får hørt for- og motargumenter og tenkt gjennom disse.
Når dagen er omme skal dere uttrykke deres egen mening i en spørreundersøkelse.
Svarene behandles anonymt, og blir oversendt byrådet i Bergen som skal behandle det formelt som innspill i den politiske prosessen.

Og med det gjenstår det bare å si lykke til!

Avrunding:

Dere har nå vært i grupper og diskutert utviklingen av Dokken. 
Dere har snakket om utfylling i sjø, om sosial boligpolitikk, Cruisetrafikk og ferger.

Dere har også snakket om Bilfrie områder.


Jeg har vært innom flere grupperom og vært flue på veggen, og jeg har sett mange gode diskusjoner.

Jeg har blitt klokere i løpet av dagen, og jeg håper også dere opplever at denne dagen har vært nyttig for dere.

Som jeg har nevnt flere ganger vil deres meninger spilles inn til politikerne i Bergen.
Det som konkret spilles inn er de svarene dere gir i undersøkelsen dere nå skal gjennomføre når arrangementet er over.
Det er derfor veldig viktig at dere fullfører denne. 
Undersøkelsen åpnet i dag, og dere skal ha fått en egen epost med lenke til denne. 
Dere trenger referansenummeret som dere fikk i invitasjonsbrevet for å svare på undersøkelsen.
Om dere ikke finner det, så kan dere ta kontakt med meg ved å svare på eposten.

Jeg oppfordrer sterkt til at dere tar den nå med en gang, slik at dere sikrer at deres stemmer blir hørt.
Om dere ikke tar den, så får dere ikke formidlet deres meninger til byrådet, og det er jo derfor dere har brukt hele denne dagen på å diskutere Bergens framtid

Takk for i dag, takk for at du stilte opp, og ta undersøkelsen! Ha en fortsatt fin helg!


